name: socshea
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#----------------- PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  dio: ^5.7.0
  intl: ^0.19.0
  logger: ^2.3.0
  lottie: ^3.1.2
  image_picker: ^1.1.2
  url_launcher: ^6.2.6
  connectivity_plus: ^2.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  dartz: ^0.10.1
  go_router: ^14.3.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  shared_preferences: ^2.3.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.6.9
  equatable: ^2.0.5


  # Product Specific
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.8

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.4


#----------------- ./ PACKAGES END -----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS -----------------#

  assets:
    - assets/logos/
    - assets/animations/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/auth/

  #----------------- LOCAL FONTS -----------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800