// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBRzlLCC31mPr1x5eNWb6txNBFu-FMvgs',
    appId: '1:928192164910:web:0176144399d74780b19bbf',
    messagingSenderId: '928192164910',
    projectId: 'socsheaapp',
    authDomain: 'socsheaapp.firebaseapp.com',
    storageBucket: 'socsheaapp.appspot.com',
    measurementId: 'G-ET3X9QGYM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0w51PdgxBDWyQOBjhMQvBOvVPQQ27gcQ',
    appId: '1:928192164910:android:2d0ed883805cf433b19bbf',
    messagingSenderId: '928192164910',
    projectId: 'socsheaapp',
    storageBucket: 'socsheaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcP-ErmCa5Xb3egTyw95IZoWU-4jN5U0',
    appId: '1:928192164910:ios:9f32386e21865354b19bbf',
    messagingSenderId: '928192164910',
    projectId: 'socsheaapp',
    storageBucket: 'socsheaapp.appspot.com',
    iosBundleId: 'com.example.socshea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcP-ErmCa5Xb3egTyw95IZoWU-4jN5U0',
    appId: '1:928192164910:ios:9f32386e21865354b19bbf',
    messagingSenderId: '928192164910',
    projectId: 'socsheaapp',
    storageBucket: 'socsheaapp.appspot.com',
    iosBundleId: 'com.example.socshea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBRzlLCC31mPr1x5eNWb6txNBFu-FMvgs',
    appId: '1:928192164910:web:cc0268beb4a5f28fb19bbf',
    messagingSenderId: '928192164910',
    projectId: 'socsheaapp',
    authDomain: 'socsheaapp.firebaseapp.com',
    storageBucket: 'socsheaapp.appspot.com',
    measurementId: 'G-7992JSNY91',
  );
}
